name: Dart CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.70'
    - name: Install dependencies
      run: flutter pub get
    - name: Static Analysis
      run: flutter analyze
    - name: Run tests
      run: flutter test
